INSERT INTO sis.SIS_TAB_CONTROL_SCRIPT (RESPONSABLE,

                                        NOMBRE_SCRIPT,
                                        DESCRIPCION,
                                        FECHA_EJECUCION,
                                        NUMERO_OT)
     VALUES ('Iván Aguilera',
             '(001)[AT.SIS] IA CONCEDE GRANTS ENDECA F3.sql',
             'CREA GRANTS de SIS a ENDECA, ENDECA Fase 3',
             SYSDATE,
             'ENDECA FASE 3');
COMMIT;             
GRANT SELECT ON SIS.SIS_TAB_DOCU_1      TO ENDECA;
GRANT SELECT ON SIS.SIS_TAB_DOCU_2      TO ENDECA;
GRANT SELECT ON SIS.SIS_TAB_DOCU_3      TO ENDECA;
GRANT SELECT ON SIS.SIS_TAB_DOCU_11     TO ENDECA;
GRANT SELECT ON SIS.SIS_TAB_DOCU_32     TO ENDECA;
GRANT SELECT ON SIS.SIS_TAB_DOCU_33     TO ENDECA;
GRANT SELECT ON SIS.SIS_TAB_DOCU_34     TO ENDECA;
GRANT SELECT ON SIS.SIS_TAB_CIERRECASO  TO ENDECA;
-- GRANT AGREGADOS PASO A PRODUCCION
GRANT SELECT ON SIS.SIS_TAB_TIPCIECA	TO ENDECA;
GRANT SELECT ON SIS.SIS_TAB_TIPEVEAIS	TO ENDECA;
GRANT SELECT ON SIS.SIS_TAB_TIPELEVA	TO ENDECA;
GRANT SELECT ON SIS.SIS_TAB_nodoHD		TO ENDECA;

COMMIT;  