INSERT INTO sis.SIS_TAB_CONTROL_SCRIPT 
(RESPONSABLE, NOMBRE_SCRIPT, DESCRIPCION, FECHA_EJECUCION, NUMERO_OT ) 
VALUES ( 
 'Diego Soto', 
 '(001)[AT.SIS] DS MD SIS_TAB_COMU.sql', 
 'Se modifican códigos externos de comunas según especificación FONASA',  
  SYSDATE, 
  'SIGG-ME577'); 
 -----------------------------------------------

UPDATE SIS.SIS_TAB_COMU SET COMU_DSC_CODALTER='01402' WHERE CONVERT(REPLACE(UPPER(COMU_DSC_NOMBRE),'Ñ','N'), 'US7ASCII') LIKE CONVERT(REPLACE(UPPER('CAMINA'),'Ñ','N'), 'US7ASCII');
UPDATE SIS.SIS_TAB_COMU SET COMU_DSC_CODALTER='01404' WHERE CONVERT(REPLACE(UPPER(COMU_DSC_NOMBRE),'Ñ','N'), 'US7ASCII') LIKE CONVERT(REPLACE(UPPER('HUARA'),'Ñ','N'), 'US7ASCII');
UPDATE SIS.SIS_TAB_COMU SET COMU_DSC_CODALTER='05802' WHERE CONVERT(REPLACE(UPPER(COMU_DSC_NOMBRE),'Ñ','N'), 'US7ASCII') LIKE CONVERT(REPLACE(UPPER('LIMACHE'),'Ñ','N'), 'US7ASCII');
UPDATE SIS.SIS_TAB_COMU SET COMU_DSC_CODALTER='05803' WHERE CONVERT(REPLACE(UPPER(COMU_DSC_NOMBRE),'Ñ','N'), 'US7ASCII') LIKE CONVERT(REPLACE(UPPER('OLMUE'),'Ñ','N'), 'US7ASCII');
UPDATE SIS.SIS_TAB_COMU SET COMU_DSC_CODALTER='01405' WHERE CONVERT(REPLACE(UPPER(COMU_DSC_NOMBRE),'Ñ','N'), 'US7ASCII') LIKE CONVERT(REPLACE(UPPER('PICA'),'Ñ','N'), 'US7ASCII');
UPDATE SIS.SIS_TAB_COMU SET COMU_DSC_CODALTER='01401' WHERE CONVERT(REPLACE(UPPER(COMU_DSC_NOMBRE),'Ñ','N'), 'US7ASCII') LIKE CONVERT(REPLACE(UPPER('POZO ALMONTE'),'Ñ','N'), 'US7ASCII');
UPDATE SIS.SIS_TAB_COMU SET COMU_DSC_CODALTER='05801' WHERE CONVERT(REPLACE(UPPER(COMU_DSC_NOMBRE),'Ñ','N'), 'US7ASCII') LIKE CONVERT(REPLACE(UPPER('QUILPUE'),'Ñ','N'), 'US7ASCII');
UPDATE SIS.SIS_TAB_COMU SET COMU_DSC_CODALTER='05804' WHERE CONVERT(REPLACE(UPPER(COMU_DSC_NOMBRE),'Ñ','N'), 'US7ASCII') LIKE CONVERT(REPLACE(UPPER('VILLA ALEMANA'),'Ñ','N'), 'US7ASCII');
commit;