set echo on;

@'(001) [AT.SIS] DS MD DROP_OBJETOS_BD.sql';
@'(002) [AT.SIS] DS MD CREACION_TABLA_INPUTBUFFER.sql';
@'(003) [AT.SIS] DS MD SPLIT_TBL TYPE.sql';
@'(004) [AT.SIS] DS MD CREACION_SECUENCIAS.sql';
@'(005) [AT.SIS] DS MD SIS_PCK_HELPER.pks.sql';
@'(006) [AT.SIS] DS MD SIS_PCK_HELPER.pkb.sql';
@'(007) [AT.SIS] DS MD SIS_PCK_PRESTACION.pks.sql';
@'(008) [AT.SIS] DS MD SIS_PCK_PRESTACION.pkb.sql';
@'(009) [AT.SIS] DS MD SIS_PCK_EVEGAROPAT.pks.sql';
@'(010) [AT.SIS] DS MD SIS_PCK_EVEGAROPAT.pkb.sql';
@'(011) [AT.SIS] DS MD GRANT_OBJETOS_BD.sql';

exit;