set echo on;


@'(001) [AT.SIS] DS MD SIS_TAB_CONTROL_SCRIPT.sql';
@'(002) [AT.SIS] DS MD SIS_SEQ_PROBLSALUD.sql';
@'(003) [AT.SIS] DS MD SIS_SEQ_FAMRAMA.sql';
@'(004) [AT.SIS] DS MD SIS_SEQ_PRESTACION.sql';
@'(005) [AT.SIS] DS MD SPLIT_TBL TYPE.sql';
@'(006) [AT.SIS] DS MD SIS_PCK_HELPER.pks.sql';
@'(007) [AT.SIS] DS MD SIS_PCK_HELPER.pkb.sql';
@'(008) [AT.SIS] DS MD SIS_PCK_PRESTACION.pks.sql';
@'(009) [AT.SIS] DS MD SIS_PCK_PRESTACION.pkb.sql';
@'(010) [AT.SIS] LG MD VENCER SIS_TAB_PROBLSALUD.sql';
@'(011) [AT.SIS] DS MD SIS_TAB_FAMRAMAPRES.sql';	



exit;