INSERT INTO sis.SIS_TAB_CONTROL_SCRIPT (RESPONSABLE,

                                        NOMBRE_SCRIPT,
                                        DESCRIPCION,
                                        FECHA_EJECUCION,
                                        NUMERO_OT)
     VALUES ('Iván Aguilera',
             '(001)[AT.ENDECA] IA CREA 8 TABLAS ENDECA F3.sql',
             'Crea tablas ENDECA Fase 3',
             SYSDATE,
             'ENDECA FASE 3');
COMMIT;             
--------------------------------------------------------------------------------

--DROP TABLE ENDECA.ENDECA_TAB_CAC CASCADE CONSTRAINTS;

CREATE TABLE ENDECA.ENDECA_TAB_CAC
(
  CPROCESO_ID_PROCESO  NUMBER(15)               NOT NULL,
  ID_CAC               NUMBER(12),
  ID_CASO              NUMBER(12),
  FECHA_CAC            DATE,
  HORA_CAC             VARCHAR2(6 BYTE),
  FOLIO_DOCUMENTO      NUMBER(12),
  COD_ESTABLECIM       NUMBER(12),
  COD_ESPECIALIDAD     NUMBER(12),
  CAUSAL_CIERRE_CASO   NUMBER(5),
  COD_PROFESIONAL      NUMBER(12),
  FEC_DIGITACION       DATE,
  USUARIO_DIGITA       NUMBER(12),
  UNIDAD_DIGITA        NUMBER(12)
)
TABLESPACE ENDECA_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--DROP TABLE ENDECA.ENDECA_TAB_CC CASCADE CONSTRAINTS;

CREATE TABLE ENDECA.ENDECA_TAB_CC
(
  CPROCESO_ID_PROCESO  NUMBER(15)               NOT NULL,
  ID_CC                NUMBER(12),
  ID_CASO              NUMBER(12),
  FECHA_CC             DATE,
  HORA_CC              VARCHAR2(6 BYTE),
  FOLIO_DOCUMENTO      NUMBER(12),
  COD_ESTABLECIM       NUMBER(12),
  COD_ESPECIALIDAD     NUMBER(12),
  CAUSAL_CIERRE_CASO   NUMBER(5),
  COD_PROFESIONAL      NUMBER(12),
  FEC_DIGITACION       DATE,
  USUARIO_DIGITA       NUMBER(12),
  UNIDAD_DIGITA        NUMBER(12)
)
TABLESPACE ENDECA_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--DROP TABLE ENDECA.ENDECA_TAB_EXCGO CASCADE CONSTRAINTS;

CREATE TABLE ENDECA.ENDECA_TAB_EXCGO
(
  CPROCESO_ID_PROCESO  NUMBER(15)               NOT NULL,
  ID_EXCGO             NUMBER(12),
  ID_CASO              NUMBER(12),
  FECHA_EXCGO          DATE,
  HORA_EXCGO           VARCHAR2(6 BYTE),
  COD_ESTABLECIM       NUMBER(12),
  COD_ESPECIALIDAD     NUMBER(12),
  CODIGO_GO            NUMBER(12),
  CAUSAL_EXCEPCION     NUMBER(5),
  COD_PROFESIONAL      NUMBER(12),
  FEC_DIGITACION       DATE,
  USUARIO_DIGITA       NUMBER(12),
  UNIDAD_DIGITA        NUMBER(12)
)
TABLESPACE ENDECA_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--DROP TABLE ENDECA.ENDECA_TAB_HD CASCADE CONSTRAINTS;

CREATE TABLE ENDECA.ENDECA_TAB_HD
(
  CPROCESO_ID_PROCESO  NUMBER(15)               NOT NULL,
  ID_HD                NUMBER(12),
  ID_CASO              NUMBER(12),
  FECHA_HD             DATE,
  HORA_HD              VARCHAR2(6 BYTE),
  COD_ESTABLECIM       NUMBER(12),
  COD_ESPECIALIDAD     NUMBER(12),
  COD_RAMA             NUMBER(12),
  ESTADO_PS_HD         NUMBER(12),
  RUN_PROFESIONAL      NUMBER(8),
  DV_PROFESIONAL       VARCHAR2(1 BYTE),
  FEC_DIGITACION       DATE,
  USUARIO_DIGITA       NUMBER(12),
  UNIDAD_DIGITA        NUMBER(12)
)
TABLESPACE ENDECA_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--DROP TABLE ENDECA.ENDECA_TAB_IPD CASCADE CONSTRAINTS;

CREATE TABLE ENDECA.ENDECA_TAB_IPD
(
  CPROCESO_ID_PROCESO  NUMBER(15)               NOT NULL,
  ID_IPD               NUMBER(12),
  ID_CASO              NUMBER(12),
  FOLIO_IPD            NUMBER(12),
  FECHA_IPD            DATE,
  HORA_IPD             VARCHAR2(6 BYTE),
  COD_ESTABLECIM       NUMBER(12),
  COD_ESPECIALIDAD     VARCHAR2(50 BYTE),
  CONFIRMADESCARTA     NUMBER(1),
  COD_RAMA             NUMBER(12),
  DIAGESP_PS           NUMBER(1),
  RUN_PROFESIONAL      NUMBER(8),
  DV_PROFESIONAL       VARCHAR2(1 BYTE),
  FEC_DIGITACION       DATE,
  USUARIO_DIGITA       NUMBER(12),
  UNIDAD_DIGITA        NUMBER(12)
)
TABLESPACE ENDECA_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--DROP TABLE ENDECA.ENDECA_TAB_OA CASCADE CONSTRAINTS;

CREATE TABLE ENDECA.ENDECA_TAB_OA
(
  CPROCESO_ID_PROCESO  NUMBER(15)               NOT NULL,
  ID_OA                NUMBER(12),
  ID_CASO              NUMBER(12),
  FECHA_OA             DATE,
  HORA_OA              VARCHAR2(6 BYTE),
  COD_ESTABLECIM       NUMBER(12),
  COD_ESPECIALIDAD     NUMBER(12),
  RUN_PROFESIONAL      NUMBER(8),
  DV_PROFESIONAL       VARCHAR2(1 BYTE),
  FEC_DIGITACION       DATE,
  USUARIO_DIGITA       NUMBER(12),
  UNIDAD_DIGITA        NUMBER(12),
  FOLIO_OA             NUMBER(12)
)
TABLESPACE ENDECA_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--DROP TABLE ENDECA.ENDECA_TAB_OAPO CASCADE CONSTRAINTS;

CREATE TABLE ENDECA.ENDECA_TAB_OAPO
(
  CPROCESO_ID_PROCESO      NUMBER(15)           NOT NULL,
  ID_OA                    NUMBER(12),
  COD_PRESTACION           NUMBER(12),
  DERIVACION_PO            NUMBER(2),
  ESPECIALIDAD_DESTINO     NUMBER(12),
  EXTRASISTEMA             NUMBER(1),
  PRESTADOR_EXTRASISTEMA   VARCHAR2(256 BYTE),
  ESTABLECIMIENTO_DESTINO  NUMBER(12)
)
TABLESPACE ENDECA_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--DROP TABLE ENDECA.ENDECA_TAB_SIC CASCADE CONSTRAINTS;

CREATE TABLE ENDECA.ENDECA_TAB_SIC
(
  CPROCESO_ID_PROCESO  NUMBER(15)               NOT NULL,
  ID_SIC               NUMBER(12),
  ID_CASO              NUMBER(12),
  FOLIO_SIC            NUMBER(12),
  FECHA_SIC            DATE,
  HORA_SIC             VARCHAR2(6 BYTE),
  ESTABLORIGEN         NUMBER(12),
  ESPECORIGEN          NUMBER(12),
  ESTABLDESTINO        NUMBER(12),
  ESPECDESTINO         NUMBER(12),
  ES_AUGE              NUMBER(2),
  DERIVADA_PARA        NUMBER(2),
  COD_RAMA             NUMBER(12),
  RUN_PROFESIONAL      NUMBER(8),
  DV_PROFESIONAL       VARCHAR2(1 BYTE),
  FEC_DIGITACION       DATE,
  USUARIO_DIGITA       NUMBER(12),
  UNIDAD_DIGITA        NUMBER(12)
)
TABLESPACE ENDECA_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
