INSERT INTO sis.SIS_TAB_CONTROL_SCRIPT 
(RESPONSABLE, NOMBRE_SCRIPT, DESCRIPCION, FECHA_EJECUCION, NUMERO_OT ) 
VALUES ( 
 'Diego Soto', 
 '(001)[AT.SIS] DS MD VUELTA_ATRAS.sql', 
 'VUELTA ATRAS',  
  SYSDATE, 
  'SIGG-ME577'); 
 -----------------------------------------------

UPDATE SIS.SIS_TAB_COMU SET COMU_DSC_CODALTER='01102' WHERE CONVERT(UPPER(COMU_DSC_NOMBRE), 'US7ASCII') LIKE CONVERT(UPPER('Camina'), 'US7ASCII');
UPDATE SIS.SIS_TAB_COMU SET COMU_DSC_CODALTER='01104' WHERE CONVERT(UPPER(COMU_DSC_NOMBRE), 'US7ASCII') LIKE CONVERT(UPPER('Huara'), 'US7ASCII');
UPDATE SIS.SIS_TAB_COMU SET COMU_DSC_CODALTER='05505' WHERE CONVERT(UPPER(COMU_DSC_NOMBRE), 'US7ASCII') LIKE CONVERT(UPPER('Limache'), 'US7ASCII');
UPDATE SIS.SIS_TAB_COMU SET COMU_DSC_CODALTER='05507' WHERE CONVERT(UPPER(COMU_DSC_NOMBRE), 'US7ASCII') LIKE CONVERT(UPPER('Olmue'), 'US7ASCII');
UPDATE SIS.SIS_TAB_COMU SET COMU_DSC_CODALTER='01105' WHERE CONVERT(UPPER(COMU_DSC_NOMBRE), 'US7ASCII') LIKE CONVERT(UPPER('Pica'), 'US7ASCII');
UPDATE SIS.SIS_TAB_COMU SET COMU_DSC_CODALTER='01106' WHERE CONVERT(UPPER(COMU_DSC_NOMBRE), 'US7ASCII') LIKE CONVERT(UPPER('Pozo Almonte'), 'US7ASCII');
UPDATE SIS.SIS_TAB_COMU SET COMU_DSC_CODALTER='05106' WHERE CONVERT(UPPER(COMU_DSC_NOMBRE), 'US7ASCII') LIKE CONVERT(UPPER('Quilpue'), 'US7ASCII');
UPDATE SIS.SIS_TAB_COMU SET COMU_DSC_CODALTER='05108' WHERE CONVERT(UPPER(COMU_DSC_NOMBRE), 'US7ASCII') LIKE CONVERT(UPPER('Villa Alemana'), 'US7ASCII');
COMMIT;