set echo on;

@'(001) [AT.NCAT] DS MD DROP_OBJETOS_BD.sql';
@'(002) [AT.NCAT] DS MD CREACION_SECUENCIAS.sql';
@'(003) [AT.NCAT] DS MD NCAT_PCK_UNION.pks.sql';
@'(004) [AT.NCAT] DS MD NCAT_PCK_UNION.pkb.sql';
@'(005) [AT.NCAT] DS MD GRANT_OBJETOS_BD.sql';

exit;